// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: ova-serial-api.proto

package ova_serial_api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSerialRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title   string `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Genre   string `protobuf:"bytes,3,opt,name=Genre,proto3" json:"Genre,omitempty"`
	Year    uint32 `protobuf:"varint,4,opt,name=Year,proto3" json:"Year,omitempty"`
	Seasons uint32 `protobuf:"varint,5,opt,name=Seasons,proto3" json:"Seasons,omitempty"`
}

func (x *CreateSerialRequestV1) Reset() {
	*x = CreateSerialRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ova_serial_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSerialRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSerialRequestV1) ProtoMessage() {}

func (x *CreateSerialRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_ova_serial_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSerialRequestV1.ProtoReflect.Descriptor instead.
func (*CreateSerialRequestV1) Descriptor() ([]byte, []int) {
	return file_ova_serial_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSerialRequestV1) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateSerialRequestV1) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSerialRequestV1) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *CreateSerialRequestV1) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CreateSerialRequestV1) GetSeasons() uint32 {
	if x != nil {
		return x.Seasons
	}
	return 0
}

type CreateSerialResponseV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateSerialResponseV1) Reset() {
	*x = CreateSerialResponseV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ova_serial_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSerialResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSerialResponseV1) ProtoMessage() {}

func (x *CreateSerialResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_ova_serial_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSerialResponseV1.ProtoReflect.Descriptor instead.
func (*CreateSerialResponseV1) Descriptor() ([]byte, []int) {
	return file_ova_serial_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSerialResponseV1) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetSerialRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetSerialRequestV1) Reset() {
	*x = GetSerialRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ova_serial_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSerialRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSerialRequestV1) ProtoMessage() {}

func (x *GetSerialRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_ova_serial_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSerialRequestV1.ProtoReflect.Descriptor instead.
func (*GetSerialRequestV1) Descriptor() ([]byte, []int) {
	return file_ova_serial_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetSerialRequestV1) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetSerialResponseV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Serial *SerialV1 `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
}

func (x *GetSerialResponseV1) Reset() {
	*x = GetSerialResponseV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ova_serial_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSerialResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSerialResponseV1) ProtoMessage() {}

func (x *GetSerialResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_ova_serial_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSerialResponseV1.ProtoReflect.Descriptor instead.
func (*GetSerialResponseV1) Descriptor() ([]byte, []int) {
	return file_ova_serial_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetSerialResponseV1) GetSerial() *SerialV1 {
	if x != nil {
		return x.Serial
	}
	return nil
}

type ListSerialsResponseV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Serials []*SerialV1 `protobuf:"bytes,1,rep,name=serials,proto3" json:"serials,omitempty"`
}

func (x *ListSerialsResponseV1) Reset() {
	*x = ListSerialsResponseV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ova_serial_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSerialsResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSerialsResponseV1) ProtoMessage() {}

func (x *ListSerialsResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_ova_serial_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSerialsResponseV1.ProtoReflect.Descriptor instead.
func (*ListSerialsResponseV1) Descriptor() ([]byte, []int) {
	return file_ova_serial_api_proto_rawDescGZIP(), []int{4}
}

func (x *ListSerialsResponseV1) GetSerials() []*SerialV1 {
	if x != nil {
		return x.Serials
	}
	return nil
}

type RemoveSerialRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemoveSerialRequestV1) Reset() {
	*x = RemoveSerialRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ova_serial_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveSerialRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSerialRequestV1) ProtoMessage() {}

func (x *RemoveSerialRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_ova_serial_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSerialRequestV1.ProtoReflect.Descriptor instead.
func (*RemoveSerialRequestV1) Descriptor() ([]byte, []int) {
	return file_ova_serial_api_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveSerialRequestV1) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SerialV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId  uint64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title   string `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	Genre   string `protobuf:"bytes,4,opt,name=Genre,proto3" json:"Genre,omitempty"`
	Year    uint32 `protobuf:"varint,5,opt,name=Year,proto3" json:"Year,omitempty"`
	Seasons uint32 `protobuf:"varint,6,opt,name=Seasons,proto3" json:"Seasons,omitempty"`
}

func (x *SerialV1) Reset() {
	*x = SerialV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ova_serial_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SerialV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerialV1) ProtoMessage() {}

func (x *SerialV1) ProtoReflect() protoreflect.Message {
	mi := &file_ova_serial_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerialV1.ProtoReflect.Descriptor instead.
func (*SerialV1) Descriptor() ([]byte, []int) {
	return file_ova_serial_api_proto_rawDescGZIP(), []int{6}
}

func (x *SerialV1) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SerialV1) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SerialV1) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SerialV1) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *SerialV1) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *SerialV1) GetSeasons() uint32 {
	if x != nil {
		return x.Seasons
	}
	return 0
}

var File_ova_serial_api_proto protoreflect.FileDescriptor

var file_ova_serial_api_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6f, 0x76, 0x61, 0x2d, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x2d, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6f, 0x76, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x8a, 0x01, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x65,
	0x6e, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x47, 0x65, 0x6e, 0x72, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x59, 0x65, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x59, 0x65, 0x61, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x22, 0x28,
	0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x24, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x47,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x56, 0x31, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x76, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x56, 0x31, 0x52,
	0x06, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x22, 0x4b, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x53,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31,
	0x12, 0x32, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x76, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x56, 0x31, 0x52, 0x07, 0x73, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x73, 0x22, 0x27, 0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x8d, 0x01,
	0x0a, 0x08, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x56, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x65, 0x6e,
	0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x59, 0x65, 0x61, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x59,
	0x65, 0x61, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x32, 0xdf, 0x02,
	0x0a, 0x0b, 0x4f, 0x76, 0x61, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x56, 0x31, 0x12, 0x5d, 0x0a,
	0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x25, 0x2e,
	0x6f, 0x76, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x56, 0x31, 0x1a, 0x26, 0x2e, 0x6f, 0x76, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x12, 0x54, 0x0a, 0x09,
	0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x22, 0x2e, 0x6f, 0x76, 0x61, 0x2e,
	0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x1a, 0x23, 0x2e,
	0x6f, 0x76, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x56, 0x31, 0x12, 0x4c, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x25, 0x2e, 0x6f, 0x76, 0x61, 0x2e,
	0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31,
	0x12, 0x4d, 0x0a, 0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x12, 0x25, 0x2e, 0x6f, 0x76, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42,
	0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x7a,
	0x6f, 0x6e, 0x76, 0x61, 0x2f, 0x6f, 0x76, 0x61, 0x2d, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x2d,
	0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6f, 0x76, 0x61, 0x2d, 0x73, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x2d, 0x61, 0x70, 0x69, 0x3b, 0x6f, 0x76, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ova_serial_api_proto_rawDescOnce sync.Once
	file_ova_serial_api_proto_rawDescData = file_ova_serial_api_proto_rawDesc
)

func file_ova_serial_api_proto_rawDescGZIP() []byte {
	file_ova_serial_api_proto_rawDescOnce.Do(func() {
		file_ova_serial_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_ova_serial_api_proto_rawDescData)
	})
	return file_ova_serial_api_proto_rawDescData
}

var file_ova_serial_api_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ova_serial_api_proto_goTypes = []interface{}{
	(*CreateSerialRequestV1)(nil),  // 0: ova.serial.api.CreateSerialRequestV1
	(*CreateSerialResponseV1)(nil), // 1: ova.serial.api.CreateSerialResponseV1
	(*GetSerialRequestV1)(nil),     // 2: ova.serial.api.GetSerialRequestV1
	(*GetSerialResponseV1)(nil),    // 3: ova.serial.api.GetSerialResponseV1
	(*ListSerialsResponseV1)(nil),  // 4: ova.serial.api.ListSerialsResponseV1
	(*RemoveSerialRequestV1)(nil),  // 5: ova.serial.api.RemoveSerialRequestV1
	(*SerialV1)(nil),               // 6: ova.serial.api.SerialV1
	(*emptypb.Empty)(nil),          // 7: google.protobuf.Empty
}
var file_ova_serial_api_proto_depIdxs = []int32{
	6, // 0: ova.serial.api.GetSerialResponseV1.serial:type_name -> ova.serial.api.SerialV1
	6, // 1: ova.serial.api.ListSerialsResponseV1.serials:type_name -> ova.serial.api.SerialV1
	0, // 2: ova.serial.api.OvaSerialV1.CreateSerial:input_type -> ova.serial.api.CreateSerialRequestV1
	2, // 3: ova.serial.api.OvaSerialV1.GetSerial:input_type -> ova.serial.api.GetSerialRequestV1
	7, // 4: ova.serial.api.OvaSerialV1.ListSerials:input_type -> google.protobuf.Empty
	5, // 5: ova.serial.api.OvaSerialV1.RemoveSerial:input_type -> ova.serial.api.RemoveSerialRequestV1
	1, // 6: ova.serial.api.OvaSerialV1.CreateSerial:output_type -> ova.serial.api.CreateSerialResponseV1
	3, // 7: ova.serial.api.OvaSerialV1.GetSerial:output_type -> ova.serial.api.GetSerialResponseV1
	4, // 8: ova.serial.api.OvaSerialV1.ListSerials:output_type -> ova.serial.api.ListSerialsResponseV1
	7, // 9: ova.serial.api.OvaSerialV1.RemoveSerial:output_type -> google.protobuf.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ova_serial_api_proto_init() }
func file_ova_serial_api_proto_init() {
	if File_ova_serial_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ova_serial_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSerialRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ova_serial_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSerialResponseV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ova_serial_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSerialRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ova_serial_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSerialResponseV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ova_serial_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSerialsResponseV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ova_serial_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveSerialRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ova_serial_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SerialV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ova_serial_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ova_serial_api_proto_goTypes,
		DependencyIndexes: file_ova_serial_api_proto_depIdxs,
		MessageInfos:      file_ova_serial_api_proto_msgTypes,
	}.Build()
	File_ova_serial_api_proto = out.File
	file_ova_serial_api_proto_rawDesc = nil
	file_ova_serial_api_proto_goTypes = nil
	file_ova_serial_api_proto_depIdxs = nil
}
